version: "3"

services:
  db:
    image: postgres # container image to be used
    restart: always
    depends_on:
      - rabbitmq
    ports:
      # expose ports in “host:container” format
      - 5432:5432
    environment:
      #env variables to pass into the container
      POSTGRES_PASSWORD: pass123
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_nodejs
networks:
  rabbitmq_nodejs:
    driver: bridge
